### ISSUE TITLE
Anycubic Kobra printer Klipper firmware will do filament Change during the print job.

### ISSUE THREAD

**Issue by Jomageri** [printers-for-people/catboat#35]
Hello There.

Thank for your amazing job and help.

Firmware from the factory (Anycubic Kobra Small) will not do filament color change even if you set it on the slicer.
I have a custom firmware (ZombieFirmware) in my printer that will include M600 code to do it.

Example of what the printer is doing with the custom ZombieFirmware:
-So the printer will stop at layer high set in the slicer during the print job.
-Then hotend will move to the home position.
-Retract 50mm of filament.
-Then you can change manually the filament with the other one (different color).
-Once you select the pause option on the display.
-The filament will be extruded 50mm.
-Then the hotend will move from the home position to resume printing.

This post is a question as I am not able to find the answer on Google, Or I haven't found it yet.

If I flash my small Kobra printer with Klipper firmware (/catboat/config/printer-anycubic-kobra-2022.cfg), will this allow me to do filament color change during the print job?

Thanks in advance.

**Comment by Jookia** [comment]
Hello there! Klipper and thus this branch does not come with M600 support. Instead you are expected to add a M600 macro that tells Klipper to do the things you just mentioned. There is an example for this in https://github.com/Klipper3d/klipper/blob/master/config/sample-macros.cfg

Here are some resources that may help you:
https://www.youtube.com/watch?v=D2-W1aTK8xU
