### ISSUE TITLE
Replace install scripts

### ISSUE THREAD

**Issue by Jookia** [printers-for-people/catboat#8]
The current install scripts are kind of crufty, we should replace it with a standardized systemd unit and a guide on setting it up on a user's distribution.

Pre-installed distro images with all tools needed for running a printer should be provided elsewhere.

**Comment by kozross** [comment]
I reckon KIAUH in the short term is fine. I ultimately set mine up from scratch as well, because I'm like that, but KIAUH seems to have become the go-to solution.

Does it work outside of Debian's ecosystem?

**Comment by Jookia** [comment]
As far as I know, no.

**Comment by Jookia** [comment]
I actually see that the README has install instructions, so I'll just close this for now.
